/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/l0calh0st/loki-operator/pkg/apis/lokioperator.l0calh0st.cn/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePromtails implements PromtailInterface
type FakePromtails struct {
	Fake *FakeLokioperatorV1alpha1
	ns   string
}

var promtailsResource = schema.GroupVersionResource{Group: "lokioperator.l0calh0st.cn", Version: "v1alpha1", Resource: "promtails"}

var promtailsKind = schema.GroupVersionKind{Group: "lokioperator.l0calh0st.cn", Version: "v1alpha1", Kind: "Promtail"}

// Get takes name of the promtail, and returns the corresponding promtail object, and an error if there is any.
func (c *FakePromtails) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Promtail, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(promtailsResource, c.ns, name), &v1alpha1.Promtail{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Promtail), err
}

// List takes label and field selectors, and returns the list of Promtails that match those selectors.
func (c *FakePromtails) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PromtailList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(promtailsResource, promtailsKind, c.ns, opts), &v1alpha1.PromtailList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PromtailList{ListMeta: obj.(*v1alpha1.PromtailList).ListMeta}
	for _, item := range obj.(*v1alpha1.PromtailList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested promtails.
func (c *FakePromtails) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(promtailsResource, c.ns, opts))

}

// Create takes the representation of a promtail and creates it.  Returns the server's representation of the promtail, and an error, if there is any.
func (c *FakePromtails) Create(ctx context.Context, promtail *v1alpha1.Promtail, opts v1.CreateOptions) (result *v1alpha1.Promtail, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(promtailsResource, c.ns, promtail), &v1alpha1.Promtail{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Promtail), err
}

// Update takes the representation of a promtail and updates it. Returns the server's representation of the promtail, and an error, if there is any.
func (c *FakePromtails) Update(ctx context.Context, promtail *v1alpha1.Promtail, opts v1.UpdateOptions) (result *v1alpha1.Promtail, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(promtailsResource, c.ns, promtail), &v1alpha1.Promtail{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Promtail), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePromtails) UpdateStatus(ctx context.Context, promtail *v1alpha1.Promtail, opts v1.UpdateOptions) (*v1alpha1.Promtail, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(promtailsResource, "status", c.ns, promtail), &v1alpha1.Promtail{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Promtail), err
}

// Delete takes name of the promtail and deletes it. Returns an error if one occurs.
func (c *FakePromtails) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(promtailsResource, c.ns, name, opts), &v1alpha1.Promtail{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePromtails) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(promtailsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.PromtailList{})
	return err
}

// Patch applies the patch and returns the patched promtail.
func (c *FakePromtails) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Promtail, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(promtailsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Promtail{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Promtail), err
}
