/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	lokioperatorl0calh0stcnv1alpha1 "github.com/l0calh0st/loki-operator/pkg/apis/lokioperator.l0calh0st.cn/v1alpha1"
	versioned "github.com/l0calh0st/loki-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/l0calh0st/loki-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/l0calh0st/loki-operator/pkg/client/listers/lokioperator.l0calh0st.cn/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PromtailInformer provides access to a shared informer and lister for
// Promtails.
type PromtailInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.PromtailLister
}

type promtailInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPromtailInformer constructs a new informer for Promtail type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPromtailInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPromtailInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPromtailInformer constructs a new informer for Promtail type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPromtailInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.LokioperatorV1alpha1().Promtails(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.LokioperatorV1alpha1().Promtails(namespace).Watch(context.TODO(), options)
			},
		},
		&lokioperatorl0calh0stcnv1alpha1.Promtail{},
		resyncPeriod,
		indexers,
	)
}

func (f *promtailInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPromtailInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *promtailInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&lokioperatorl0calh0stcnv1alpha1.Promtail{}, f.defaultInformer)
}

func (f *promtailInformer) Lister() v1alpha1.PromtailLister {
	return v1alpha1.NewPromtailLister(f.Informer().GetIndexer())
}
