/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/l0calh0st/loki-operator/pkg/apis/lokioperator.l0calh0st.cn/v1alpha1"
	scheme "github.com/l0calh0st/loki-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PromtailsGetter has a method to return a PromtailInterface.
// A group's client should implement this interface.
type PromtailsGetter interface {
	Promtails(namespace string) PromtailInterface
}

// PromtailInterface has methods to work with Promtail resources.
type PromtailInterface interface {
	Create(ctx context.Context, promtail *v1alpha1.Promtail, opts v1.CreateOptions) (*v1alpha1.Promtail, error)
	Update(ctx context.Context, promtail *v1alpha1.Promtail, opts v1.UpdateOptions) (*v1alpha1.Promtail, error)
	UpdateStatus(ctx context.Context, promtail *v1alpha1.Promtail, opts v1.UpdateOptions) (*v1alpha1.Promtail, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Promtail, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.PromtailList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Promtail, err error)
	PromtailExpansion
}

// promtails implements PromtailInterface
type promtails struct {
	client rest.Interface
	ns     string
}

// newPromtails returns a Promtails
func newPromtails(c *LokioperatorV1alpha1Client, namespace string) *promtails {
	return &promtails{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the promtail, and returns the corresponding promtail object, and an error if there is any.
func (c *promtails) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Promtail, err error) {
	result = &v1alpha1.Promtail{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("promtails").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Promtails that match those selectors.
func (c *promtails) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PromtailList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.PromtailList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("promtails").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested promtails.
func (c *promtails) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("promtails").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a promtail and creates it.  Returns the server's representation of the promtail, and an error, if there is any.
func (c *promtails) Create(ctx context.Context, promtail *v1alpha1.Promtail, opts v1.CreateOptions) (result *v1alpha1.Promtail, err error) {
	result = &v1alpha1.Promtail{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("promtails").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(promtail).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a promtail and updates it. Returns the server's representation of the promtail, and an error, if there is any.
func (c *promtails) Update(ctx context.Context, promtail *v1alpha1.Promtail, opts v1.UpdateOptions) (result *v1alpha1.Promtail, err error) {
	result = &v1alpha1.Promtail{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("promtails").
		Name(promtail.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(promtail).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *promtails) UpdateStatus(ctx context.Context, promtail *v1alpha1.Promtail, opts v1.UpdateOptions) (result *v1alpha1.Promtail, err error) {
	result = &v1alpha1.Promtail{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("promtails").
		Name(promtail.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(promtail).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the promtail and deletes it. Returns an error if one occurs.
func (c *promtails) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("promtails").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *promtails) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("promtails").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched promtail.
func (c *promtails) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Promtail, err error) {
	result = &v1alpha1.Promtail{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("promtails").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
