apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: promtail-cluster-role
spec:
  - apiGroups:
      - ""
    resources:
      - "pod"
    verbs:
      - get
      - watch
      - list
